package com.hbm.ntm.block;

public enum LegacyMachineRenderProfile {
    DEFAULT,
    ANNIHILATOR_UV_SCROLL,
    STEAM_ENGINE_ITEM_PREVIEW,
    INDUSTRIAL_TURBINE_ITEM_PREVIEW,
    ARC_FURNACE_STATIC_PREVIEW,
    RADGEN_STATIC_SPECIAL,
    BATTERY_REDD_STATIC_SPECIAL,
    CRYSTALLIZER_STATIC_SPECIAL,
    TURBOFAN_ITEM_PREVIEW
}
