package com.hbm.ntm.block;

public enum LegacyMachineRenderProfile {
    DEFAULT,
    ANNIHILATOR_UV_SCROLL,
    STEAM_ENGINE_ITEM_PREVIEW,
    INDUSTRIAL_TURBINE_ITEM_PREVIEW,
    COMPRESSOR_RUNNING_PARTS,
    COMPRESSOR_COMPACT_RUNNING_FANS,
    POWERED_CONDENSER_FANS,
    COMBUSTION_ENGINE_DOOR_CANISTER,
    FIREBOX_HEATER,
    HEAT_BOILER,
    PUMP_RUNNING_PARTS,
    ARC_FURNACE_STATIC_PREVIEW,
    RADGEN_STATIC_SPECIAL,
    BATTERY_REDD_STATIC_SPECIAL,
    CRYSTALLIZER_STATIC_SPECIAL,
    TURBOFAN_ITEM_PREVIEW
}
