package com.hbm.ntm.recipe;

import com.hbm.inventory.material.MaterialShapes;
import com.hbm.inventory.material.Mats;
import com.hbm.inventory.material.Mats.MaterialStack;
import com.hbm.inventory.material.NTMMaterial;
import com.hbm.inventory.material.NTMMaterial.SmeltingBehavior;
import com.hbm.ntm.item.FoundryScrapsItem;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.RecipeManager;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.Nullable;

public final class CrucibleSmeltingRecipeRuntime {
    private CrucibleSmeltingRecipeRuntime() {
    }

    public static boolean isItemSmeltable(@Nullable Level level, ItemStack stack) {
        return !getSmeltingMaterialsFromItem(level, stack).isEmpty();
    }

    public static List<MaterialStack> getSmeltingMaterialsFromItem(@Nullable Level level, ItemStack stack) {
        return getSmeltingMaterialsFromItem(level == null ? null : level.getRecipeManager(), stack);
    }

    public static List<MaterialStack> getSmeltingMaterialsFromItem(@Nullable RecipeManager recipeManager,
            ItemStack stack) {
        List<MaterialStack> smelting = new ArrayList<>();
        for (MaterialStack material : baseMaterials(recipeManager, stack)) {
            if (material == null || material.material == null) {
                continue;
            }
            NTMMaterial smeltsInto = material.material.smeltsInto == null
                    ? material.material
                    : material.material.smeltsInto;
            if (smeltsInto.smeltable == SmeltingBehavior.SMELTABLE
                    || smeltsInto.smeltable == SmeltingBehavior.ADDITIVE) {
                smelting.add(new MaterialStack(smeltsInto,
                        material.amount * material.material.convOut / material.material.convIn));
            }
        }
        return smelting;
    }

    public static List<MaterialStack> baseMaterials(@Nullable Level level, ItemStack stack) {
        return baseMaterials(level == null ? null : level.getRecipeManager(), stack);
    }

    public static List<MaterialStack> baseMaterials(@Nullable RecipeManager recipeManager, ItemStack stack) {
        if (stack.isEmpty()) {
            return List.of();
        }
        if (recipeManager != null) {
            for (CrucibleSmeltingRecipe recipe : smeltingRecipes(recipeManager)) {
                if (recipe.input().test(stack, true)) {
                    return recipe.output();
                }
            }
        }
        return Mats.getMaterialsFromItem(stack);
    }

    public static List<DisplayRecipe> displayRecipes(@Nullable RecipeManager recipeManager) {
        Map<String, DisplayRecipe> recipes = new LinkedHashMap<>();
        if (recipeManager != null) {
            for (CrucibleSmeltingRecipe recipe : smeltingRecipes(recipeManager)) {
                addDisplayRecipe(recipes, recipe.input(), recipe.input().displayStacks(), recipe.output(),
                        recipe.sourceOrder());
            }
        }
        addAutogeneratedDisplayRecipes(recipes);
        return List.copyOf(recipes.values());
    }

    private static List<CrucibleSmeltingRecipe> smeltingRecipes(RecipeManager recipeManager) {
        return recipeManager.getAllRecipesFor(ModRecipes.CRUCIBLE_SMELTING.type().get()).stream()
                .sorted(Comparator.comparingInt(CrucibleSmeltingRecipe::sourceOrder)
                        .thenComparing(recipe -> recipe.getId().toString()))
                .toList();
    }

    private static void addAutogeneratedDisplayRecipes(Map<String, DisplayRecipe> recipes) {
        for (NTMMaterial material : Mats.orderedList) {
            NTMMaterial smeltsInto = material.smeltsInto == null ? material : material.smeltsInto;
            if (smeltsInto.smeltable != SmeltingBehavior.SMELTABLE
                    && smeltsInto.smeltable != SmeltingBehavior.ADDITIVE) {
                continue;
            }
            for (MaterialShapes shape : MaterialShapes.allShapes) {
                if (shape.noAutogen) {
                    continue;
                }
                HbmIngredient ingredient = HbmIngredient.legacyOre(shape.make(material), 1);
                List<ItemStack> inputs = ingredient.displayStacks();
                if (inputs.isEmpty()) {
                    continue;
                }
                int amount = shape.q(1) * material.convOut / material.convIn;
                addDisplayRecipe(recipes, ingredient, inputs, List.of(new MaterialStack(smeltsInto, amount)),
                        Integer.MAX_VALUE);
            }
        }
    }

    private static void addDisplayRecipe(Map<String, DisplayRecipe> recipes, HbmIngredient ingredient,
            List<ItemStack> inputs, List<MaterialStack> outputs, int sourceOrder) {
        List<ItemStack> outputStacks = outputs.stream()
                .map(stack -> FoundryScrapsItem.create(stack, true))
                .filter(stack -> !stack.isEmpty())
                .toList();
        if (inputs.isEmpty() || outputStacks.isEmpty()) {
            return;
        }
        recipes.putIfAbsent(displayKey(ingredient, outputs), new DisplayRecipe(inputs, outputStacks, sourceOrder));
    }

    private static String displayKey(HbmIngredient ingredient, List<MaterialStack> outputs) {
        StringBuilder builder = new StringBuilder(ingredient.diagnosticKey()).append("=>");
        for (MaterialStack output : outputs) {
            if (output != null && !output.isEmpty()) {
                builder.append(output.material.id).append(':').append(output.amount).append(';');
            }
        }
        return builder.toString();
    }

    public record DisplayRecipe(List<ItemStack> inputs, List<ItemStack> outputs, int sourceOrder) {
        public DisplayRecipe {
            inputs = inputs.stream().map(ItemStack::copy).toList();
            outputs = outputs.stream().map(ItemStack::copy).toList();
        }
    }
}
