modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"

[[mods]]
modId="hbm_ntm_rebirth"
version="0.1.7beta"
displayName="HBM-NTM: Rebirth"
authors="HBM/NTM original contributors; HBM-NTM: Rebirth port contributors"
description='''Forge 1.20.1 migration of Hbm's Nuclear Tech, rebuilt from the 1.7.10 source codebase with modern Forge systems.'''

[[dependencies."hbm_ntm_rebirth"]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies."hbm_ntm_rebirth"]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies."hbm_ntm_rebirth"]]
modId="jei"
mandatory=false
versionRange="[15.20.0,)"
ordering="AFTER"
side="BOTH"
