package com.hbm.ntm.item;

import com.hbm.ntm.util.BobMathUtil;
import com.hbm.ntm.util.RtgPelletRuntime;
import java.util.List;
import java.util.Locale;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.Nullable;

public class RtgPelletItem extends Item {
    private static final String[] FACTS = {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    public RtgPelletItem(Properties properties) {
        super(properties.stacksTo(1));
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        ItemStack stack = player.getItemInHand(hand);
        if (!RtgPelletRuntime.isRegularPellet(stack)) {
            return InteractionResultHolder.pass(stack);
        }
        if (!level.isClientSide) {
            player.sendSystemMessage(Component.literal(FACTS[level.random.nextInt(FACTS.length)])
                    .withStyle(ChatFormatting.YELLOW));
            level.playSound(null, player.getX(), player.getY(), player.getZ(),
                    SoundEvents.EXPERIENCE_ORB_PICKUP, SoundSource.PLAYERS, 1.0F, 1.0F);
        }
        return InteractionResultHolder.sidedSuccess(stack, level.isClientSide);
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return RtgPelletRuntime.doesDecay(stack)
                && RtgPelletRuntime.lifespan(stack) != RtgPelletRuntime.maxLifespan(stack);
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        return Math.round(13.0F * (float) (1.0D - RtgPelletRuntime.durabilityForDisplay(stack)));
    }

    @Override
    public void appendHoverText(ItemStack stack, @Nullable Level level, List<Component> tooltip, TooltipFlag flag) {
        super.appendHoverText(stack, level, tooltip, flag);
        tooltip.add(Component.translatable(getDescriptionId(stack) + ".desc").withStyle(ChatFormatting.GRAY));
        tooltip.add(Component.translatable("desc.item.rtgHeat", tooltipHeat(stack)).withStyle(ChatFormatting.GRAY));
        if (RtgPelletRuntime.doesDecay(stack)) {
            ItemStack decayItem = RtgPelletRuntime.decayItem(stack);
            tooltip.add(Component.translatable("desc.item.rtgDecay", decayItem.getHoverName(), decayItem.getCount())
                    .withStyle(ChatFormatting.GRAY));
            tooltip.add(Component.literal(BobMathUtil.toPercentage(
                    RtgPelletRuntime.lifespan(stack), RtgPelletRuntime.maxLifespan(stack)))
                    .withStyle(ChatFormatting.GRAY));
            if (flag.isAdvanced()) {
                long lifespan = RtgPelletRuntime.lifespan(stack);
                long maxLifespan = RtgPelletRuntime.maxLifespan(stack);
                tooltip.add(Component.literal("EXTENDED INFO:").withStyle(ChatFormatting.GRAY));
                tooltip.add(Component.literal(String.format(Locale.US, "%s / %s ticks", lifespan, maxLifespan))
                        .withStyle(ChatFormatting.GRAY));
                String[] timeLeft = BobMathUtil.ticksToDate(lifespan);
                String[] maxLife = BobMathUtil.ticksToDate(maxLifespan);
                tooltip.add(Component.literal(String.format(Locale.US, "Time remaining: %s y, %s d, %s h",
                        (Object[]) timeLeft)).withStyle(ChatFormatting.GRAY));
                tooltip.add(Component.literal(String.format(Locale.US, "Maximum life: %s y, %s d, %s h",
                        (Object[]) maxLife)).withStyle(ChatFormatting.GRAY));
            }
        }
    }

    public short getHeat(ItemStack stack) {
        return (short) RtgPelletRuntime.baseHeat(stack);
    }

    public boolean getDoesDecay(ItemStack stack) {
        return RtgPelletRuntime.doesDecay(stack);
    }

    public long getMaxLifespan(ItemStack stack) {
        return RtgPelletRuntime.maxLifespan(stack);
    }

    public long getLifespan(ItemStack stack) {
        return RtgPelletRuntime.lifespan(stack);
    }

    public ItemStack getDecayItem(ItemStack stack) {
        return RtgPelletRuntime.decayItem(stack);
    }

    public void decay(ItemStack stack) {
        RtgPelletRuntime.decay(stack);
    }

    public double getDurabilityForDisplay(ItemStack stack) {
        return RtgPelletRuntime.durabilityForDisplay(stack);
    }

    public String getData(ItemStack stack) {
        return String.format(Locale.US, "%s (%s HE/t) %s",
                stack.getHoverName().getString(),
                RtgPelletRuntime.baseHeat(stack),
                RtgPelletRuntime.doesDecay(stack) ? " (decays)" : "");
    }

    public static ItemStack handleDecay(ItemStack stack, RtgPelletItem instance) {
        return RtgPelletRuntime.handleDecay(stack);
    }

    public static short getScaledPower(RtgPelletItem fuel, ItemStack stack) {
        return (short) RtgPelletRuntime.scaledHeat(stack);
    }

    private static int tooltipHeat(ItemStack stack) {
        return RtgPelletRuntime.doesDecay(stack)
                && com.hbm.ntm.config.RtgConfig.scaleRtgPower()
                ? RtgPelletRuntime.scaledHeat(stack)
                : RtgPelletRuntime.baseHeat(stack);
    }
}
