package com.hbm.ntm.registry;

import com.hbm.ntm.HbmNtm;
import com.hbm.ntm.sound.LegacySirenTrack;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

public final class ModSounds {
    public static final DeferredRegister<SoundEvent> SOUNDS =
            DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, HbmNtm.MOD_ID);

    public static final RegistryObject<SoundEvent> BLOCK_PRESS_OPERATE = register("block.press_operate");
    public static final RegistryObject<SoundEvent> BLOCK_MOTOR = register("block.motor");
    public static final RegistryObject<SoundEvent> BLOCK_ENGINE = register("block.engine");
    public static final RegistryObject<SoundEvent> BLOCK_LARGE_TURBINE_RUNNING = register("block.large_turbine_running");
    public static final RegistryObject<SoundEvent> BLOCK_CHUNGUS_TURBINE_RUNNING = register("block.chungus_turbine_running");
    public static final RegistryObject<SoundEvent> BLOCK_FEL = register("block.fel");
    public static final RegistryObject<SoundEvent> BLOCK_ELECTRIC_HUM = register("block.electric_hum");
    public static final RegistryObject<SoundEvent> BLOCK_FUSION_REACTOR_RUNNING = register("block.fusion_reactor_running");
    public static final RegistryObject<SoundEvent> BLOCK_BOILER_GROAN = register("block.boiler_groan");
    public static final RegistryObject<SoundEvent> BLOCK_CENTRIFUGE_OPERATE = register("block.centrifuge_operate");
    public static final RegistryObject<SoundEvent> BLOCK_TURBOFAN_OPERATE = register("block.turbofan_operate");
    public static final RegistryObject<SoundEvent> BLOCK_DAMAGE = register("block.damage");
    public static final RegistryObject<SoundEvent> BLOCK_HEPHAESTUS_RUNNING = register("block.hephaestus_running");
    public static final RegistryObject<SoundEvent> BLOCK_STEAM_ENGINE_OPERATE = register("block.steam_engine_operate");
    public static final RegistryObject<SoundEvent> BLOCK_REACTOR_LOOP = register("block.reactor_loop");
    public static final RegistryObject<SoundEvent> BLOCK_TURBINEGAS_STARTUP = register("block.turbinegas_startup");
    public static final RegistryObject<SoundEvent> BLOCK_TURBINEGAS_RUNNING = register("block.turbinegas_running");
    public static final RegistryObject<SoundEvent> BLOCK_TURBINEGAS_SHUTDOWN = register("block.turbinegas_shutdown");
    public static final RegistryObject<SoundEvent> BLOCK_ASSEMBLER_OPERATE = register("block.assembler_operate");
    public static final RegistryObject<SoundEvent> BLOCK_ASSEMBLER_STRIKE = register("block.assembler_strike");
    public static final RegistryObject<SoundEvent> BLOCK_ASSEMBLER_START = register("block.assembler_start");
    public static final RegistryObject<SoundEvent> BLOCK_ASSEMBLER_STOP = register("block.assembler_stop");
    public static final RegistryObject<SoundEvent> BLOCK_ASSEMBLER_CUT = register("block.assembler_cut");
    public static final RegistryObject<SoundEvent> BLOCK_CHEMPLANT_OPERATE = register("block.chemplant_operate");
    public static final RegistryObject<SoundEvent> BLOCK_CHEMICAL_PLANT = register("block.chemical_plant");
    public static final RegistryObject<SoundEvent> BLOCK_PIPE_PLACED = register("block.pipe_placed");
    public static final RegistryObject<SoundEvent> BLOCK_DEBRIS = register("block.debris");
    public static final RegistryObject<SoundEvent> BLOCK_REACTOR_START = register("block.reactor_start");
    public static final RegistryObject<SoundEvent> BLOCK_BOILER = register("block.boiler");
    public static final RegistryObject<SoundEvent> BLOCK_PYRO_OPERATE = register("block.pyro_operate");
    public static final RegistryObject<SoundEvent> BLOCK_SONAR_PING = register("block.sonar_ping");
    public static final RegistryObject<SoundEvent> BLOCK_SOYUZ_READY = register("block.soyuz_ready");
    public static final RegistryObject<SoundEvent> BLOCK_BOBBLE = register("block.bobble");
    public static final RegistryObject<SoundEvent> BLOCK_BROADCAST_1 = register("block.broadcast1");
    public static final RegistryObject<SoundEvent> BLOCK_BROADCAST_2 = register("block.broadcast2");
    public static final RegistryObject<SoundEvent> BLOCK_BROADCAST_3 = register("block.broadcast3");
    public static final RegistryObject<SoundEvent> BLOCK_CHUNGUS_LEVER = register("block.chungus_lever");
    public static final RegistryObject<SoundEvent> BLOCK_CLOSE_C = register("block.close_c");
    public static final RegistryObject<SoundEvent> BLOCK_CLOSE_DOOR = register("block.close_door");
    public static final RegistryObject<SoundEvent> BLOCK_CRATE_BREAK = register("block.crate_break");
    public static final RegistryObject<SoundEvent> BLOCK_CRATE_CLOSE = register("block.crate_close");
    public static final RegistryObject<SoundEvent> BLOCK_CRATE_OPEN = register("block.crate_open");
    public static final RegistryObject<SoundEvent> BLOCK_DIESEL_OPERATE = register("block.diesel_operate");
    public static final RegistryObject<SoundEvent> BLOCK_FENSU_HUM = register("block.fensu_hum");
    public static final RegistryObject<SoundEvent> BLOCK_HORN_FAR_DUAL = register("block.horn_far_dual");
    public static final RegistryObject<SoundEvent> BLOCK_HORN_FAR_SINGLE = register("block.horn_far_single");
    public static final RegistryObject<SoundEvent> BLOCK_HORN_NEAR_DUAL = register("block.horn_near_dual");
    public static final RegistryObject<SoundEvent> BLOCK_HORN_NEAR_SINGLE = register("block.horn_near_single");
    public static final RegistryObject<SoundEvent> BLOCK_HUNDUNS_MAGNIFICENT_HOWL = register("block.hunduns_magnificent_howl");
    public static final RegistryObject<SoundEvent> BLOCK_IGENERATOR_OPERATE = register("block.igenerator_operate");
    public static final RegistryObject<SoundEvent> BLOCK_LEVER_LARGE = register("block.lever_large");
    public static final RegistryObject<SoundEvent> BLOCK_LEVER_START = register("block.lever_start");
    public static final RegistryObject<SoundEvent> BLOCK_LEVER_STOP = register("block.lever_stop");
    public static final RegistryObject<SoundEvent> BLOCK_LOCK_HANG = register("block.lock_hang");
    public static final RegistryObject<SoundEvent> BLOCK_LOCK_OPEN = register("block.lock_open");
    public static final RegistryObject<SoundEvent> BLOCK_METAL_IMPACT = register("block.metal_impact");
    public static final RegistryObject<SoundEvent> BLOCK_MINER_OPERATE = register("block.miner_operate");
    public static final RegistryObject<SoundEvent> BLOCK_MISSILE_ASSEMBLY = register("block.missile_assembly");
    public static final RegistryObject<SoundEvent> BLOCK_MISSILE_ASSEMBLY2 = register("block.missile_assembly2");
    public static final RegistryObject<SoundEvent> BLOCK_OPEN_C = register("block.open_c");
    public static final RegistryObject<SoundEvent> BLOCK_OPEN_DOOR = register("block.open_door");
    public static final RegistryObject<SoundEvent> BLOCK_RBMK_AZ5_COVER = register("block.rbmk_az5_cover");
    public static final RegistryObject<SoundEvent> BLOCK_RBMK_EXPLOSION = register("block.rbmk_explosion");
    public static final RegistryObject<SoundEvent> BLOCK_REACTOR_STOP = register("block.reactor_stop");
    public static final RegistryObject<SoundEvent> BLOCK_SCREM = register("block.screm");
    public static final RegistryObject<SoundEvent> BLOCK_SHUTDOWN = register("block.shutdown");
    public static final RegistryObject<SoundEvent> BLOCK_SPARK = register("block.spark");
    public static final RegistryObject<SoundEvent> BLOCK_SQUEAKY_TOY = register("block.squeaky_toy");
    public static final RegistryObject<SoundEvent> BLOCK_STORAGE_CLOSE = register("block.storage_close");
    public static final RegistryObject<SoundEvent> BLOCK_STORAGE_OPEN = register("block.storage_open");
    public static final RegistryObject<SoundEvent> BLOCK_VAULT_SCRAPE = register("block.vault_scrape");
    public static final RegistryObject<SoundEvent> BLOCK_VAULT_SCRAPE_NEW = register("block.vault_scrape_new");
    public static final RegistryObject<SoundEvent> BLOCK_VAULT_THUD = register("block.vault_thud");
    public static final RegistryObject<SoundEvent> BLOCK_VAULT_THUD_NEW = register("block.vault_thud_new");
    public static final RegistryObject<SoundEvent> BLOCK_WARN_OVERSPEED = register("block.warn_overspeed");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_1 = register("tool.geiger1");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_2 = register("tool.geiger2");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_3 = register("tool.geiger3");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_4 = register("tool.geiger4");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_5 = register("tool.geiger5");
    public static final RegistryObject<SoundEvent> TOOL_GEIGER_6 = register("tool.geiger6");
    public static final RegistryObject<SoundEvent> TOOL_TECH_BOOP = register("tool.tech_boop");
    public static final RegistryObject<SoundEvent> TOOL_TECH_BLEEP = register("tool.tech_bleep");
    public static final RegistryObject<SoundEvent> TOOL_RADAWAY = register("tool.radaway");
    public static final RegistryObject<SoundEvent> TOOL_GASMASK_SCREW = register("tool.gasmask_screw");
    public static final RegistryObject<SoundEvent> TOOL_PIN_BREAK = register("tool.pin_break");
    public static final RegistryObject<SoundEvent> TOOL_SYRINGE = register("item.syringe");
    public static final RegistryObject<SoundEvent> ITEM_BATTERY = register("item.battery");
    public static final RegistryObject<SoundEvent> ITEM_BOLTGUN = register("item.boltgun");
    public static final RegistryObject<SoundEvent> ITEM_GASMASK_SCREW = register("item.gasmask_screw");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_1 = register("item.geiger1");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_2 = register("item.geiger2");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_3 = register("item.geiger3");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_4 = register("item.geiger4");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_5 = register("item.geiger5");
    public static final RegistryObject<SoundEvent> ITEM_GEIGER_6 = register("item.geiger6");
    public static final RegistryObject<SoundEvent> ITEM_JETPACK_TANK = register("item.jetpack_tank");
    public static final RegistryObject<SoundEvent> ITEM_PIN_BREAK = register("item.pin_break");
    public static final RegistryObject<SoundEvent> ITEM_PIN_UNLOCK = register("item.pin_unlock");
    public static final RegistryObject<SoundEvent> ITEM_RADAWAY = register("item.radaway");
    public static final RegistryObject<SoundEvent> ITEM_REPAIR = register("item.repair");
    public static final RegistryObject<SoundEvent> ITEM_SPRAY = register("item.spray");
    public static final RegistryObject<SoundEvent> ITEM_TECH_BLEEP = register("item.tech_bleep");
    public static final RegistryObject<SoundEvent> ITEM_TECH_BOOP = register("item.tech_boop");
    public static final RegistryObject<SoundEvent> ITEM_UNPACK = register("item.unpack");
    public static final RegistryObject<SoundEvent> ITEM_UPGRADE_PLUG = register("item.upgrade_plug");
    public static final RegistryObject<SoundEvent> ITEM_VICE = register("item.vice");
    public static final RegistryObject<SoundEvent> STEP_METAL = register("step.metal");
    public static final RegistryObject<SoundEvent> STEP_IRON_JUMP = register("step.iron_jump");
    public static final RegistryObject<SoundEvent> STEP_IRON_LAND = register("step.iron_land");
    public static final RegistryObject<SoundEvent> STEP_IRON = register("step.iron");
    public static final RegistryObject<SoundEvent> STEP_METAL_BLOCK = register("step.metal_block");
    public static final RegistryObject<SoundEvent> STEP_POWERED = register("step.powered");
    public static final RegistryObject<SoundEvent> PLAYER_COUGH = register("player.cough");
    public static final RegistryObject<SoundEvent> PLAYER_VOMIT = register("player.vomit");
    public static final RegistryObject<SoundEvent> PLAYER_GULP = register("player.gulp");
    public static final RegistryObject<SoundEvent> PLAYER_GROAN = register("player.groan");
    public static final RegistryObject<SoundEvent> POTATOS_RANDOM = register("potatos.random");
    public static final RegistryObject<SoundEvent> MISC_NULL_CHOPPER = register("misc.null_chopper");
    public static final RegistryObject<SoundEvent> MISC_NULL_CRASHING = register("misc.null_crashing");
    public static final RegistryObject<SoundEvent> MISC_NULL_MINE = register("misc.null_mine");
    public static final RegistryObject<SoundEvent> MUSIC_RECORD_LAMBDA_CORE = register("music.record_lambda_core");
    public static final RegistryObject<SoundEvent> MUSIC_RECORD_SECTOR_SWEEP = register("music.record_sector_sweep");
    public static final RegistryObject<SoundEvent> MUSIC_RECORD_VORTAL_COMBAT = register("music.record_vortal_combat");
    public static final RegistryObject<SoundEvent> MUSIC_TRANSMISSION = register("music.transmission");
    public static final RegistryObject<SoundEvent> ENTITY_CYBERCRAB = register("entity.cybercrab");
    public static final RegistryObject<SoundEvent> ENTITY_DUCC = register("entity.ducc");
    public static final RegistryObject<SoundEvent> ENTITY_MEGAQUACC = register("entity.megaquacc");
    public static final RegistryObject<SoundEvent> ENTITY_SIEGE_DEATH = register("entity.siege_death");
    public static final RegistryObject<SoundEvent> ENTITY_SIEGE_HURT = register("entity.siege_hurt");
    public static final RegistryObject<SoundEvent> ENTITY_SIEGE_IDLE = register("entity.siege_idle");
    public static final RegistryObject<SoundEvent> ENTITY_UFO_BEAM = register("entity.ufo_beam");
    public static final RegistryObject<SoundEvent> ENTITY_UFO_BLAST = register("entity.ufo_blast");
    public static final RegistryObject<SoundEvent> ENTITY_SLICER = register("entity.slicer");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_FLYING_LOOP = register("entity.chopper_flying_loop");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_CRASHING_LOOP = register("entity.chopper_crashing_loop");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_MINE_LOOP = register("entity.chopper_mine_loop");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_DROP = register("entity.chopper_drop");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_CHARGE = register("entity.chopper_charge");
    public static final RegistryObject<SoundEvent> ENTITY_CHOPPER_DAMAGE = register("entity.chopper_damage");
    public static final RegistryObject<SoundEvent> ENTITY_SOYUZ_TAKEOFF = register("entity.soyuz_takeoff");
    public static final RegistryObject<SoundEvent> ENTITY_OLD_EXPLOSION = register("entity.old_explosion");
    public static final RegistryObject<SoundEvent> ENTITY_ROCKET_TAKEOFF = register("entity.rocket_takeoff");
    public static final RegistryObject<SoundEvent> ENTITY_BOMB_DET = register("entity.bomb_det");
    public static final RegistryObject<SoundEvent> ENTITY_BOMB_WHISTLE = register("entity.bomb_whistle");
    public static final RegistryObject<SoundEvent> ENTITY_BOMBER_LOOP = register("entity.bomber_loop");
    public static final RegistryObject<SoundEvent> ENTITY_BOMBER_SMALL_LOOP = register("entity.bomber_small_loop");
    public static final RegistryObject<SoundEvent> ENTITY_PLANE_CRASH = register("entity.plane_crash");
    public static final RegistryObject<SoundEvent> ENTITY_PLANE_SHOT_DOWN = register("entity.plane_shot_down");
    public static final RegistryObject<SoundEvent> ENTITY_METEORITE_FALLING_LOOP = register("entity.meteorite_falling_loop");
    public static final RegistryObject<SoundEvent> TURRET_CHEKHOV_FIRE = register("turret.chekhov_fire");
    public static final RegistryObject<SoundEvent> TURRET_JEREMY_FIRE = register("turret.jeremy_fire");
    public static final RegistryObject<SoundEvent> TURRET_JEREMY_RELOAD = register("turret.jeremy_reload");
    public static final RegistryObject<SoundEvent> TURRET_RICHARD_FIRE = register("turret.richard_fire");
    public static final RegistryObject<SoundEvent> TURRET_HOWARD_FIRE = register("turret.howard_fire");
    public static final RegistryObject<SoundEvent> TURRET_HOWARD_RELOAD = register("turret.howard_reload");
    public static final RegistryObject<SoundEvent> TURRET_SENTRY_FIRE = register("turret.sentry_fire");
    public static final RegistryObject<SoundEvent> TURRET_SENTRY_LOCKON = register("turret.sentry_lockon");
    public static final RegistryObject<SoundEvent> TURRET_MORTAR_WHISTLE = register("turret.mortar_whistle");
    public static final RegistryObject<SoundEvent> ALARM_SOYUZED = register("alarm.soyuzed");
    public static final RegistryObject<SoundEvent> ALARM_TRAIN_HORN = register("alarm.train_horn");
    public static final RegistryObject<SoundEvent> ALARM_GAMBIT = register("alarm.gambit");
    public static final RegistryObject<SoundEvent> ALARM_CHIME = register("alarm.chime");
    public static final RegistryObject<SoundEvent> ALARM_SINGER = register("alarm.singer");
    public static final RegistryObject<SoundEvent> DOOR_TRANSITION_SEAL_OPEN = register("door.transition_seal_open");
    public static final RegistryObject<SoundEvent> DOOR_WGH_START = register("door.wgh_start");
    public static final RegistryObject<SoundEvent> DOOR_WGH_STOP = register("door.wgh_stop");
    public static final RegistryObject<SoundEvent> DOOR_ALARM6 = register("door.alarm6");
    public static final RegistryObject<SoundEvent> DOOR_SLIDING_DOOR_SHUT = register("door.sliding_door_shut");
    public static final RegistryObject<SoundEvent> DOOR_SLIDING_DOOR_OPENED = register("door.sliding_door_opened");
    public static final RegistryObject<SoundEvent> DOOR_SLIDING_DOOR_OPENING = register("door.sliding_door_opening");
    public static final RegistryObject<SoundEvent> DOOR_GARAGE_MOVE = register("door.garage_move");
    public static final RegistryObject<SoundEvent> DOOR_GARAGE_STOP = register("door.garage_stop");
    public static final RegistryObject<SoundEvent> DOOR_LEVER = register("door.lever");
    public static final RegistryObject<SoundEvent> DOOR_WGH_BIG_START = register("door.wgh_big_start");
    public static final RegistryObject<SoundEvent> DOOR_WGH_BIG_STOP = register("door.wgh_big_stop");
    public static final RegistryObject<SoundEvent> DOOR_QE_SLIDING_SHUT = register("door.qe_sliding_shut");
    public static final RegistryObject<SoundEvent> DOOR_QE_SLIDING_OPENED = register("door.qe_sliding_opened");
    public static final RegistryObject<SoundEvent> DOOR_QE_SLIDING_OPENING = register("door.qe_sliding_opening");
    public static final RegistryObject<SoundEvent> DOOR_SLIDING_SEAL_OPEN = register("door.sliding_seal_open");
    public static final RegistryObject<SoundEvent> DOOR_SLIDING_SEAL_STOP = register("door.sliding_seal_stop");
    public static final RegistryObject<SoundEvent> WEAPON_MUKE_EXPLOSION = register("weapon.muke_explosion");
    public static final RegistryObject<SoundEvent> WEAPON_NUCLEAR_EXPLOSION = register("weapon.nuclear_explosion");
    public static final RegistryObject<SoundEvent> WEAPON_FSTBMB_START = register("weapon.fstbmb_start");
    public static final RegistryObject<SoundEvent> WEAPON_FSTBMB_PING = register("weapon.fstbmb_ping");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_LARGE_NEAR = register("weapon.explosion_large_near");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_LARGE_FAR = register("weapon.explosion_large_far");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_SMALL_NEAR = register("weapon.explosion_small_near");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_SMALL_FAR = register("weapon.explosion_small_far");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_TINY = register("weapon.explosion_tiny");
    public static final RegistryObject<SoundEvent> WEAPON_EXPLOSION_MEDIUM = register("weapon.explosion_medium");
    public static final RegistryObject<SoundEvent> WEAPON_CHAINSAW = register("weapon.chainsaw");
    public static final RegistryObject<SoundEvent> WEAPON_FLAMETHROWER_SHOOT = register("weapon.flamethrower_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_ROCKET_FLAME = register("weapon.rocket_flame");
    public static final RegistryObject<SoundEvent> WEAPON_CAL_SHOOT = register("weapon.cal_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_TESLA_SHOOT = register("weapon.tesla_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_HK_SHOOT = register("weapon.hk_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_TAU_SHOOT = register("weapon.tau_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_TAU_CHARGE_LOOP = register("weapon.tau_charge_loop");
    public static final RegistryObject<SoundEvent> WEAPON_TAU_CHARGE_LOOP2 = register("weapon.tau_charge_loop2");
    public static final RegistryObject<SoundEvent> WEAPON_REVOLVER_SHOOT = register("weapon.revolver_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_REVOLVER_SHOOT_ALT = register("weapon.revolver_shoot_alt");
    public static final RegistryObject<SoundEvent> WEAPON_SHOTGUN_SHOOT = register("weapon.shotgun_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_SCHRABIDIUM_SHOOT = register("weapon.schrabidium_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_SING_FLYBY = register("weapon.sing_flyby");
    public static final RegistryObject<SoundEvent> WEAPON_RIFLE_SHOOT = register("weapon.rifle_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_RPG_SHOOT = register("weapon.rpg_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_FATMAN_SHOOT = register("weapon.fatman_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_FATMAN_RELOAD = register("weapon.fatman_reload");
    public static final RegistryObject<SoundEvent> WEAPON_FLAMETHROWER_IGNITE = register("weapon.flamethrower_ignite");
    public static final RegistryObject<SoundEvent> WEAPON_IMMOLATOR_IGNITE = register("weapon.immolator_ignite");
    public static final RegistryObject<SoundEvent> WEAPON_IMMOLATOR_SHOOT = register("weapon.immolator_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_MISSILE_TAKE_OFF = register("weapon.missile_take_off");
    public static final RegistryObject<SoundEvent> WEAPON_SPARK_SHOOT = register("weapon.spark_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_BANG = register("weapon.bang");
    public static final RegistryObject<SoundEvent> WEAPON_SLICE = register("weapon.slice");
    public static final RegistryObject<SoundEvent> WEAPON_KAPENG = register("weapon.kapeng");
    public static final RegistryObject<SoundEvent> WEAPON_LEVER_ACTION_RELOAD = register("weapon.lever_action_reload");
    public static final RegistryObject<SoundEvent> WEAPON_B92_RELOAD = register("weapon.b92_reload");
    public static final RegistryObject<SoundEvent> WEAPON_STINGER_LOCK_ON = register("weapon.stinger_lock_on");
    public static final RegistryObject<SoundEvent> WEAPON_SAW_SHOOT = register("weapon.saw_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_SPINUP = register("weapon.spinup");
    public static final RegistryObject<SoundEvent> WEAPON_SPINDOWN = register("weapon.spindown");
    public static final RegistryObject<SoundEvent> WEAPON_LASER_BANG = register("weapon.laser_bang");
    public static final RegistryObject<SoundEvent> WEAPON_UZI_SHOOT = register("weapon.uzi_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_SILENCER_SHOOT = register("weapon.silencer_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_REVOLVER_RELOAD = register("weapon.revolver_reload");
    public static final RegistryObject<SoundEvent> WEAPON_SHOTGUN_RELOAD = register("weapon.shotgun_reload");
    public static final RegistryObject<SoundEvent> WEAPON_MAG_RELOAD = register("weapon.mag_reload");
    public static final RegistryObject<SoundEvent> WEAPON_MAG_RELOAD_BOLT = register("weapon.mag_reload_bolt");
    public static final RegistryObject<SoundEvent> WEAPON_RPG_RELOAD = register("weapon.rpg_reload");
    public static final RegistryObject<SoundEvent> WEAPON_BOAT = register("weapon.boat");
    public static final RegistryObject<SoundEvent> WEAPON_TESLA = register("weapon.tesla");
    public static final RegistryObject<SoundEvent> WEAPON_FLAMER_RELOAD = register("weapon.flamer_reload");
    public static final RegistryObject<SoundEvent> WEAPON_STOP = register("weapon.stop");
    public static final RegistryObject<SoundEvent> WEAPON_BONK = register("weapon.bonk");
    public static final RegistryObject<SoundEvent> WEAPON_HKS_SHOOT = register("weapon.hks_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_BODYSPLAT = register("weapon.bodysplat");
    public static final RegistryObject<SoundEvent> WEAPON_QUADRO_RELOAD = register("weapon.quadro_reload");
    public static final RegistryObject<SoundEvent> WEAPON_WHACK = register("weapon.whack");
    public static final RegistryObject<SoundEvent> WEAPON_BALLS_LASER = register("weapon.balls_laser");
    public static final RegistryObject<SoundEvent> WEAPON_DART_SHOOT = register("weapon.dart_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_C_DEPLOY = register("weapon.c_deploy");
    public static final RegistryObject<SoundEvent> WEAPON_C_SWING = register("weapon.c_swing");
    public static final RegistryObject<SoundEvent> WEAPON_EXTINGUISHER = register("weapon.extinguisher");
    public static final RegistryObject<SoundEvent> WEAPON_ROBIN_EXPLOSION = register("weapon.robin_explosion");
    public static final RegistryObject<SoundEvent> WEAPON_SHOTGUN_PUMP = register("weapon.shotgun_pump");
    public static final RegistryObject<SoundEvent> WEAPON_SHOTGUN_PUMP_ALT = register("weapon.shotgun_pump_alt");
    public static final RegistryObject<SoundEvent> WEAPON_HICAL_SHOT = register("weapon.hical_shot");
    public static final RegistryObject<SoundEvent> WEAPON_COILGUN_RELOAD = register("weapon.coilgun_reload");
    public static final RegistryObject<SoundEvent> WEAPON_COILGUN_SHOOT = register("weapon.coilgun_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_GL_RELOAD = register("weapon.gl_reload");
    public static final RegistryObject<SoundEvent> WEAPON_GL_SHOOT = register("weapon.gl_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_GL_OPEN = register("weapon.gl_open");
    public static final RegistryObject<SoundEvent> WEAPON_GL_CLOSE = register("weapon.gl_close");
    public static final RegistryObject<SoundEvent> WEAPON_44_SHOOT = register("weapon.44_shoot");
    public static final RegistryObject<SoundEvent> WEAPON_TRAIN_IMPACT = register("weapon.train_impact");
    public static final RegistryObject<SoundEvent> WEAPON_GRENADE_BOUNCE_LEGACY = register("weapon.grenade_bounce");
    public static final RegistryObject<SoundEvent> WEAPON_D_FLASH = register("weapon.d_flash");
    public static final RegistryObject<SoundEvent> WEAPON_SWITCHMODE1 = register("weapon.switchmode1");
    public static final RegistryObject<SoundEvent> WEAPON_SWITCHMODE2 = register("weapon.switchmode2");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_BLACK_POWDER = register("weapon.fire.black_powder");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_FLAME_LOOP = register("weapon.fire.flame_loop");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_LOCKON = register("weapon.fire.lockon");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SHREDDER_CYCLE = register("weapon.fire.shredder_cycle");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_TAU = register("weapon.fire.tau");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_TAU_LOOP = register("weapon.fire.tau_loop");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_TAU_RELEASE = register("weapon.fire.tau_release");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_FATMAN = register("weapon.fire.fatman");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SMACK = register("weapon.fire.smack");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_VSTAR = register("weapon.fire.vstar");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_LOUDEST_NOISE_ON_EARTH = register("weapon.fire.loudest_noise_on_earth");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_DISINTEGRATION = register("weapon.fire.disintegration");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_LASER = register("weapon.fire.laser");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_LASER_PISTOL = register("weapon.fire.laser_pistol");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_LASER_GATLING = register("weapon.fire.laser_gatling");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SILENCED = register("weapon.fire.silenced");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_ASSAULT = register("weapon.fire.assault");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_PISTOL = register("weapon.fire.pistol");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_RIFLE = register("weapon.fire.rifle");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_RIFLE_HEAVY = register("weapon.fire.rifle_heavy");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SHOTGUN = register("weapon.fire.shotgun");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SHOTGUN_ALT = register("weapon.fire.shotgun_alt");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_SHOTGUN_AUTO = register("weapon.fire.shotgun_auto");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_GREASE_GUN = register("weapon.fire.grease_gun");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_UZI = register("weapon.fire.uzi");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_TESLA = register("weapon.fire.tesla");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_ABERRATOR = register("weapon.fire.aberrator");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_STAB = register("weapon.fire.stab");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_GRENADE = register("weapon.fire.grenade");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_AMAT = register("weapon.fire.amat");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_PISTOL_LIGHT = register("weapon.fire.pistol_light");
    public static final RegistryObject<SoundEvent> WEAPON_FIRE_MK108 = register("weapon.fire.mk108");
    public static final RegistryObject<SoundEvent> WEAPON_RICOCHET = register("weapon.ricochet");
    public static final RegistryObject<SoundEvent> WEAPON_GRENADE_BOUNCE = register("weapon.gbounce");
    public static final RegistryObject<SoundEvent> WEAPON_G_BOUNCE_LEGACY = register("weapon.g_bounce");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_BOLT_CLOSE = register("weapon.reload.bolt_close");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_BOLT_OPEN = register("weapon.reload.bolt_open");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_CLOSE_CLICK = register("weapon.reload.close_click");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_DRY_FIRE_CLICK = register("weapon.reload.dry_fire_click");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_INSERT_CANISTER = register("weapon.reload.insert_canister");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_INSERT_GRENADE = register("weapon.reload.insert_grenade");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_INSERT_LARGE = register("weapon.reload.insert_large");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_INSERT_ROCKET = register("weapon.reload.insert_rocket");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_LEVER_COCK = register("weapon.reload.lever_cock");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_MAG_INSERT = register("weapon.reload.mag_insert");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_MAG_REMOVE = register("weapon.reload.mag_remove");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_MAG_SMALL_INSERT = register("weapon.reload.mag_small_insert");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_MAG_SMALL_REMOVE = register("weapon.reload.mag_small_remove");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_OPEN_LATCH = register("weapon.reload.open_latch");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_PISTOL_COCK = register("weapon.reload.pistol_cock");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_PRESSURE_VALVE = register("weapon.reload.pressure_valve");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_REVOLVER_CLOSE = register("weapon.reload.revolver_close");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_REVOLVER_COCK = register("weapon.reload.revolver_cock");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_REVOLVER_SPIN = register("weapon.reload.revolver_spin");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_RIFLE_COCK = register("weapon.reload.rifle_cock");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_SHOTGUN_COCK = register("weapon.reload.shotgun_cock");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_SHOTGUN_COCK_OPEN = register("weapon.reload.shotgun_cock_open");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_SHOTGUN_COCK_CLOSE = register("weapon.reload.shotgun_cock_close");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_SHOTGUN_RELOAD = register("weapon.reload.shotgun_reload");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_TUBE_FWOOMP = register("weapon.reload.tube_fwoomp");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_IMPACT = register("weapon.reload.impact");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_FATMAN_FULL = register("weapon.reload.fatman_full");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_SCREW = register("weapon.reload.screw");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_GRENADE_TECH = register("weapon.reload.grenade_tech");
    public static final RegistryObject<SoundEvent> WEAPON_RELOAD_GRENADE_NUKA = register("weapon.reload.grenade_nuka");
    public static final RegistryObject<SoundEvent> WEAPON_FOLEY_GUN_WHACK = register("weapon.foley.gun_whack");
    public static final RegistryObject<SoundEvent> WEAPON_CASING_SHELL = register("weapon.casing.shell");
    public static final RegistryObject<SoundEvent> WEAPON_CASING_SMALL = register("weapon.casing.small");
    public static final RegistryObject<SoundEvent> WEAPON_CASING_MEDIUM = register("weapon.casing.medium");
    public static final RegistryObject<SoundEvent> WEAPON_CASING_LARGE = register("weapon.casing.large");
    public static final Map<LegacySirenTrack, RegistryObject<SoundEvent>> ALARM_TRACKS = registerAlarmTracks();
    public static final RegistryObject<SoundEvent> ALARM_HATCH = ALARM_TRACKS.get(LegacySirenTrack.HATCH);

    public static void register(IEventBus modBus) {
        SOUNDS.register(modBus);
    }

    public static SoundEvent geiger(int level) {
        return switch (Math.max(1, Math.min(6, level))) {
            case 2 -> TOOL_GEIGER_2.get();
            case 3 -> TOOL_GEIGER_3.get();
            case 4 -> TOOL_GEIGER_4.get();
            case 5 -> TOOL_GEIGER_5.get();
            case 6 -> TOOL_GEIGER_6.get();
            default -> TOOL_GEIGER_1.get();
        };
    }

    public static SoundEvent sirenTrack(LegacySirenTrack track) {
        RegistryObject<SoundEvent> sound = ALARM_TRACKS.get(track);
        return sound == null ? null : sound.get();
    }

    private static Map<LegacySirenTrack, RegistryObject<SoundEvent>> registerAlarmTracks() {
        EnumMap<LegacySirenTrack, RegistryObject<SoundEvent>> sounds = new EnumMap<>(LegacySirenTrack.class);
        for (LegacySirenTrack track : LegacySirenTrack.values()) {
            if (track.hasSound()) {
                sounds.put(track, register(track.eventPath()));
            }
        }
        return Collections.unmodifiableMap(sounds);
    }

    private static RegistryObject<SoundEvent> register(String name) {
        return SOUNDS.register(name, () -> SoundEvent.createVariableRangeEvent(new ResourceLocation(HbmNtm.MOD_ID, name)));
    }

    private ModSounds() {
    }
}
