package com.hbm.ntm.datagen;

import java.util.function.BiConsumer;

final class HbmFluidLangEntries {
    private static final String EN_US = """
            hazard.bacteria=Bacteria / Aerosols
            hazard.corrosive=Corrosive Fumes
            hazard.gasChlorine=Chemical Gas
            hazard.gasInert=Inert Gas / Asphxiants
            hazard.gasMonoxide=Carbon Monoxide
            hazard.light=Bright Lights
            hazard.nerveAgent=Nerve Agent
            hazard.neverProtects=Will never protect against:
            hazard.noprot=Does NOT protect against:
            hazard.particleCoarse=Airborne Particles
            hazard.particleFine=Particulates
            hazard.prot=Protects against hazards:
            hazard.sand=Eye Irritants
            hbmfluid.air=Compressed Air
            hbmfluid.airblast=Hot Air Blast
            hbmfluid.alumina=Alumina
            hbmfluid.amat=Antimatter
            hbmfluid.aromatics=Aromatic Hydrocarbons
            hbmfluid.aschrab=Antischrabidium
            hbmfluid.balefire=BF Rocket Fuel
            hbmfluid.bauxite_solution=Bauxite Solution
            hbmfluid.biofuel=Biofuel
            hbmfluid.biogas=Biogas
            hbmfluid.bitumen=Bitumen
            hbmfluid.blood=Blood
            hbmfluid.blood_hot=Hot Blood
            hbmfluid.calcium_chloride=Calciumchloride Solution
            hbmfluid.calcium_solution=Calcium Solution
            hbmfluid.carbondioxide=Carbon Dioxide
            hbmfluid.chlorine=Chlorine Gas
            hbmfluid.chlorocalcite_cleaned=Cleaned Chlorocalcite Solution
            hbmfluid.chlorocalcite_mix=Mixed Chlorocalcite Solution
            hbmfluid.chlorocalcite_solution=Chlorocalcite Solution
            hbmfluid.cholesterol=Cholesterol Solution
            hbmfluid.coalcreosote=Coal Tar Creosote
            hbmfluid.coalgas=Coal Gasoline
            hbmfluid.coalgas_leaded=Leaded Coal Gasoline
            hbmfluid.coaloil=Coal Oil
            hbmfluid.colloid=Colloid
            hbmfluid.concrete=Liquid Concrete
            hbmfluid.coolant=Coolant
            hbmfluid.coolant_hot=Hot Coolant
            hbmfluid.crackoil=Cracked Oil
            hbmfluid.crackoil_ds=Desulfurized Cracked Oil
            hbmfluid.cryogel=Cryogel
            hbmfluid.death=Osmiridic Solution
            hbmfluid.deuterium=Deuterium
            hbmfluid.dhc=Deuterated Hydrocarbon
            hbmfluid.diesel=Diesel
            hbmfluid.diesel_crack=Cracked Diesel
            hbmfluid.diesel_crack_reform=High-Cetane Cracked Diesel
            hbmfluid.diesel_reform=High-Cetane Diesel
            hbmfluid.egg=Dissolved Egg
            hbmfluid.enderjuice=Ender Juice
            hbmfluid.estradiol=Estradiol Solution
            hbmfluid.ethanol=Ethanol
            hbmfluid.fishoil=Fish Oil
            hbmfluid.flue=Flue Gas
            hbmfluid.fracksol=Fracking Solution
            hbmfluid.fullerene=Fullerene Solution
            hbmfluid.gas=Natural Gas
            hbmfluid.gas_coker=Coker Gas
            hbmfluid.gasoline=Gasoline
            hbmfluid.gasoline_leaded=Leaded Gasoline
            hbmfluid.heatingoil=Heating Oil
            hbmfluid.heatingoil_vacuum=Heavy Heating Oil
            hbmfluid.heavyoil=Heavy Oil
            hbmfluid.heavyoil_vacuum=Vacuum Heavy Oil
            hbmfluid.heavywater=Heavy Water
            hbmfluid.heavywater_hot=Hot Heavy Water
            hbmfluid.helium3=Helium-3
            hbmfluid.helium4=Helium-4
            hbmfluid.hotcrackoil=Hot Cracked Oil
            hbmfluid.hotcrackoil_ds=Desulfurized Hot Cracked Oil
            hbmfluid.hotoil=Hot Crude Oil
            hbmfluid.hotoil_ds=Desulfurized Hot Crude Oil
            hbmfluid.hotsteam=Dense Steam
            hbmfluid.hydrogen=Liquid Hydrogen
            hbmfluid.iongel=Ionic Gel
            hbmfluid.kerosene=Kerosene
            hbmfluid.kerosene_reform=Jet Fuel
            hbmfluid.lava=Lava
            hbmfluid.lead=Liquid Lead
            hbmfluid.lead_hot=Hot Liquid Lead
            hbmfluid.lightoil=Light Oil
            hbmfluid.lightoil_crack=Cracked Light Oil
            hbmfluid.lightoil_ds=Desulfurized Light Oil
            hbmfluid.lightoil_vacuum=Vacuum Light Oil
            hbmfluid.lpg=LPG
            hbmfluid.lubricant=Engine Lubricant
            hbmfluid.lye=Lye
            hbmfluid.mercury=Mercury
            hbmfluid.mug=Mug Root Beer
            hbmfluid.mug_hot=Hot Mug Root Beer
            hbmfluid.mustardgas=Mustard Gas
            hbmfluid.naphtha=Naphtha
            hbmfluid.naphtha_coker=Coker Naphtha
            hbmfluid.naphtha_crack=Cracked Naphtha
            hbmfluid.naphtha_ds=Desulfurized Naphtha
            hbmfluid.nitan=NITAN© 100 Octane Super Fuel
            hbmfluid.nitric_acid=Nitric Acid
            hbmfluid.nitroglycerin=Nitroglycerin
            hbmfluid.none=None
            hbmfluid.oil=Crude Oil
            hbmfluid.oil_coker=Coker Oil
            hbmfluid.oil_ds=Desulfurized Crude Oil
            hbmfluid.oxygen=Liquid Oxygen
            hbmfluid.oxyhydrogen=Oxyhydrogen
            hbmfluid.pain=Pandemonium(III)tantalite Solution
            hbmfluid.perfluoromethyl=Perfluoromethyl
            hbmfluid.perfluoromethyl_cold=Cold Perfluoromethyl
            hbmfluid.perfluoromethyl_hot=Hot Perfluoromethyl
            hbmfluid.peroxide=Hydrogen Peroxide
            hbmfluid.petroil=Petroil
            hbmfluid.petroil_leaded=Leaded Petroil
            hbmfluid.petroleum=Petroleum Gas
            hbmfluid.pheromone=Booster Pheromone
            hbmfluid.pheromone_m=Modified Booster Pheromone
            hbmfluid.phosgene=Phosgene
            hbmfluid.plasma_bf=Balefire Plasma
            hbmfluid.plasma_dh3=Deuterium-Helium-3 Plasma
            hbmfluid.plasma_dt=Deuterium-Tritium Plasma
            hbmfluid.plasma_hd=Hydrogen-Deuterium Plasma
            hbmfluid.plasma_ht=Hydrogen-Tritium Plasma
            hbmfluid.plasma_xm=Helium-4-Oxygen Plasma
            hbmfluid.potassium_chloride=Potassiumchloride Solution
            hbmfluid.puf6=Plutonium Hexafluoride
            hbmfluid.radiosolvent=High-Performance Solvent
            hbmfluid.reclaimed=Reclaimed Industrial Oil
            hbmfluid.redmud=Red Mud
            hbmfluid.reformate=Reformate
            hbmfluid.reformgas=Reformate Gas
            hbmfluid.salient=Salient Green
            hbmfluid.sas3=Schrabidium Trisulfide
            hbmfluid.schrabidic=Schrabidic Acid
            hbmfluid.seedslurry=Seeding Slurry
            hbmfluid.slop=Ore Slop
            hbmfluid.smear=Industrial Oil
            hbmfluid.smoke=Smoke
            hbmfluid.smoke_leaded=Leaded Smoke
            hbmfluid.smoke_poison=Poison Smoke
            hbmfluid.sodium=Liquid Sodium
            hbmfluid.sodium_aluminate=Sodium Aluminate
            hbmfluid.sodium_hot=Hot Liquid Sodium
            hbmfluid.solvent=Solvent
            hbmfluid.sourgas=Sour Gas
            hbmfluid.spentsteam=Low-Pressure Steam
            hbmfluid.steam=Steam
            hbmfluid.stellar_flux=Stellar Flux
            hbmfluid.sulfuric_acid=Sulfuric Acid
            hbmfluid.sunfloweroil=Sunflower Seed Oil
            hbmfluid.superhotsteam=Super Dense Steam
            hbmfluid.syngas=Syngas
            hbmfluid.thorium_salt=Liquid Thorium Salt
            hbmfluid.thorium_salt_depleted=Depleted Liquid Thorium Salt
            hbmfluid.thorium_salt_hot=Hot Liquid Thorium Salt
            hbmfluid.tritium=Tritium
            hbmfluid.uf6=Uranium Hexafluoride
            hbmfluid.ultrahotsteam=Ultra Dense Steam
            hbmfluid.unsaturateds=Unsaturated Hydrocarbons
            hbmfluid.vitriol=Vitriol
            hbmfluid.wastefluid=Liquid Nuclear Waste
            hbmfluid.wastegas=Gaseous Nuclear Waste
            hbmfluid.water=Water
            hbmfluid.watz=Poisonous Mud
            hbmfluid.woodoil=Wood Oil
            hbmfluid.xenon=Xenon Gas
            hbmfluid.xpjuice=Experience Juice
            hbmfluid.xylene=BTX
            """;

    private static final String ZH_CN = """
            hazard.bacteria=细菌/气溶胶
            hazard.corrosive=腐蚀性烟雾
            hazard.gasChlorine=化学气体
            hazard.gasInert=惰性气体/沥青
            hazard.gasMonoxide=一氧化碳
            hazard.light=亮光
            hazard.nerveAgent=神经毒剂
            hazard.neverProtects=无法防护：
            hazard.noprot=不能防止：
            hazard.particleCoarse=空气微粒
            hazard.particleFine=微粒
            hazard.prot=防止危险：
            hazard.sand=眼睛刺激物
            hbmfluid.air=压缩空气
            hbmfluid.airblast=热鼓风
            hbmfluid.alumina=氧化铝溶液
            hbmfluid.amat=反物质
            hbmfluid.aromatics=芳香烃
            hbmfluid.aschrab=反Sa326
            hbmfluid.balefire=野火火箭燃料
            hbmfluid.bauxite_solution=铝土矿溶液
            hbmfluid.biofuel=生物燃料
            hbmfluid.biogas=沼气
            hbmfluid.bitumen=沥青
            hbmfluid.blood=血
            hbmfluid.blood_hot=热的血
            hbmfluid.calcium_chloride=氯化钙溶液
            hbmfluid.calcium_solution=钙溶液
            hbmfluid.carbondioxide=二氧化碳
            hbmfluid.chlorine=氯气
            hbmfluid.chlorocalcite_cleaned=纯净氯方解石溶液
            hbmfluid.chlorocalcite_mix=混合氯方解石溶液
            hbmfluid.chlorocalcite_solution=氯方解石溶液
            hbmfluid.cholesterol=胆固醇溶液
            hbmfluid.coalcreosote=煤焦杂酚油
            hbmfluid.coalgas=煤汽油
            hbmfluid.coalgas_leaded=含铅煤汽油
            hbmfluid.coaloil=煤液化油
            hbmfluid.colloid=胶体
            hbmfluid.concrete=液态混凝土
            hbmfluid.coolant=冷却液
            hbmfluid.coolant_hot=热冷却液
            hbmfluid.crackoil=裂化油
            hbmfluid.crackoil_ds=脱硫裂化油
            hbmfluid.cryogel=冷凝胶
            hbmfluid.death=锇酸溶液
            hbmfluid.deuterium=氘
            hbmfluid.dhc=氘代烃
            hbmfluid.diesel=柴油
            hbmfluid.diesel_crack=裂化柴油
            hbmfluid.diesel_crack_reform=高十六烷值裂化柴油
            hbmfluid.diesel_reform=高十六烷值柴油
            hbmfluid.egg=蛋溶解液
            hbmfluid.enderjuice=末影果汁
            hbmfluid.estradiol=雌二醇溶液
            hbmfluid.ethanol=乙醇
            hbmfluid.fishoil=鱼油
            hbmfluid.flue=烟道气
            hbmfluid.fracksol=压裂液
            hbmfluid.fullerene=富勒烯溶液
            hbmfluid.gas=天然气
            hbmfluid.gas_coker=焦化气
            hbmfluid.gasoline=含铅汽油基油
            hbmfluid.gasoline_leaded=含铅汽油
            hbmfluid.heatingoil=燃油
            hbmfluid.heatingoil_vacuum=重质燃油
            hbmfluid.heavyoil=重油
            hbmfluid.heavyoil_vacuum=减压重油
            hbmfluid.heavywater=重水
            hbmfluid.heavywater_hot=高温重水
            hbmfluid.helium3=氦-3
            hbmfluid.helium4=氦-4
            hbmfluid.hotcrackoil=热裂化油
            hbmfluid.hotcrackoil_ds=热的脱硫裂化油
            hbmfluid.hotoil=热原油
            hbmfluid.hotoil_ds=热的脱硫原油
            hbmfluid.hotsteam=热蒸汽
            hbmfluid.hydrogen=液氢
            hbmfluid.iongel=离子凝胶
            hbmfluid.kerosene=煤油
            hbmfluid.kerosene_reform=喷气燃料
            hbmfluid.lava=岩浆
            hbmfluid.lead=液态铅
            hbmfluid.lead_hot=高温液态铅
            hbmfluid.lightoil=轻油
            hbmfluid.lightoil_crack=裂化轻油
            hbmfluid.lightoil_ds=脱硫轻油
            hbmfluid.lightoil_vacuum=减压轻油
            hbmfluid.lpg=液化石油气
            hbmfluid.lubricant=润滑油
            hbmfluid.lye=碱液
            hbmfluid.mercury=水银
            hbmfluid.mug=Mug牌树根饮料
            hbmfluid.mug_hot=热的Mug牌树根饮料
            hbmfluid.mustardgas=芥子气
            hbmfluid.naphtha=石脑油
            hbmfluid.naphtha_coker=焦化石脑油
            hbmfluid.naphtha_crack=裂化石脑油
            hbmfluid.naphtha_ds=脱硫石脑油
            hbmfluid.nitan=NITAN牌100号超级燃料
            hbmfluid.nitric_acid=硝酸
            hbmfluid.nitroglycerin=硝酸甘油
            hbmfluid.none=无
            hbmfluid.oil=原油
            hbmfluid.oil_coker=焦化油
            hbmfluid.oil_ds=脱硫原油
            hbmfluid.oxygen=液氧
            hbmfluid.oxyhydrogen=氢氧混合气
            hbmfluid.pain=Pn(III) 钽铁溶液
            hbmfluid.perfluoromethyl=四氟甲烷
            hbmfluid.perfluoromethyl_cold=冷四氟甲烷
            hbmfluid.perfluoromethyl_hot=热四氟甲烷
            hbmfluid.peroxide=过氧化氢
            hbmfluid.petroil=汽油
            hbmfluid.petroil_leaded=含铅石油
            hbmfluid.petroleum=石油气
            hbmfluid.pheromone=异虫信息素
            hbmfluid.pheromone_m=增强异虫信息素
            hbmfluid.phosgene=光气
            hbmfluid.plasma_bf=野火等离子体
            hbmfluid.plasma_dh3=氘-氦3 等离子体
            hbmfluid.plasma_dt=氘-氚等离子体
            hbmfluid.plasma_hd=氢-氘等离子体
            hbmfluid.plasma_ht=氢-氚等离子体
            hbmfluid.plasma_xm=液氧-氦-4等离子体
            hbmfluid.potassium_chloride=氯化钾溶液
            hbmfluid.puf6=六氟化钚
            hbmfluid.radiosolvent=高性能溶剂
            hbmfluid.reclaimed=再生油
            hbmfluid.redmud=红色泥浆
            hbmfluid.reformate=重整油
            hbmfluid.reformgas=重整气
            hbmfluid.salient=绿色液体
            hbmfluid.sas3=三硫化Sa
            hbmfluid.schrabidic=Sa酸
            hbmfluid.seedslurry=播种浆料
            hbmfluid.slop=洗矿废水
            hbmfluid.smear=工业油
            hbmfluid.smoke=烟雾
            hbmfluid.smoke_leaded=含铅烟雾
            hbmfluid.smoke_poison=有毒烟雾
            hbmfluid.sodium=液态钠
            hbmfluid.sodium_aluminate=偏铝酸钠溶液
            hbmfluid.sodium_hot=高温液态钠
            hbmfluid.solvent=有机溶剂
            hbmfluid.sourgas=高硫天然气
            hbmfluid.spentsteam=低压蒸汽
            hbmfluid.steam=蒸汽
            hbmfluid.stellar_flux=星流浆
            hbmfluid.sulfuric_acid=硫酸
            hbmfluid.sunfloweroil=葵花籽油
            hbmfluid.superhotsteam=超热蒸汽
            hbmfluid.syngas=合成气
            hbmfluid.thorium_salt=液态钍盐
            hbmfluid.thorium_salt_depleted=贫化液态钍盐
            hbmfluid.thorium_salt_hot=高温液态钍盐
            hbmfluid.tritium=氚
            hbmfluid.uf6=六氟化铀
            hbmfluid.ultrahotsteam=超浓密蒸汽
            hbmfluid.unsaturateds=不饱和烃
            hbmfluid.vitriol=硫酸盐溶液
            hbmfluid.wastefluid=液态核废料
            hbmfluid.wastegas=气态核废料
            hbmfluid.water=水
            hbmfluid.watz=毒泥浆
            hbmfluid.woodoil=木油
            hbmfluid.xenon=氙气
            hbmfluid.xpjuice=经验汁
            hbmfluid.xylene=轻质芳烃（BTX）
            """;

    static void addEnglish(BiConsumer<String, String> add) {
        addBlock(add, EN_US);
        add.accept("hbmfluid.info.hold_shift", "Hold <LSHIFT> to display more info");
    }

    static void addChinese(BiConsumer<String, String> add) {
        addBlock(add, ZH_CN);
        add.accept("hbmfluid.info.hold_shift", "按住 <LSHIFT> 显示更多信息");
    }

    private static void addBlock(BiConsumer<String, String> add, String entries) {
        for (String line : entries.split("\\R")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty()) {
                continue;
            }
            int split = trimmed.indexOf('=');
            if (split > 0) {
                add.accept(trimmed.substring(0, split), trimmed.substring(split + 1));
            }
        }
    }

    private HbmFluidLangEntries() {
    }
}
